version: 2.1
orbs:
  gh: circleci/github-cli@1.0.3
jobs:
    build_project:
        docker:
            - image: circleci/node:14.18.1-browsers
        working_directory: ~/react-native-cli-templates
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
            - run:
                  name: Install dependencies
                  command: |
                      yarn install
            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package.json" }}
            - run:
                  name: Prettier Check
                  command: |
                      yarn prettier:check
            - run:
                  name: Lint
                  command: |
                      yarn lint

    publish:
        docker:
          - image: circleci/node:14.18.1-browsers
        steps:
            - checkout
            - run:
                name: Authenticate with registry
                command: |
                  echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
                  echo "//registry.yarnpkg.com/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            - run:
                name: Publish @brightlayer-ui/react-native-template-blank
                command: |
                  cd blank && yarn publish:package -b $CIRCLE_BRANCH
            - run:
                name: Publish @brightlayer-ui/react-native-template-blank-typescript
                command: |
                  cd blank-typescript && yarn publish:package -b $CIRCLE_BRANCH
            - run:
                name: Publish @brightlayer-ui/react-native-template-routing
                command: |
                  cd routing && yarn publish:package -b $CIRCLE_BRANCH
            - run:
                name: Publish @brightlayer-ui/react-native-template-routing-typescript
                command: |
                  cd routing-typescript && yarn publish:package -b $CIRCLE_BRANCH
            - run:
                name: Publish @brightlayer-ui/react-native-template-authentication
                command: |
                  cd authentication && yarn publish:package -b $CIRCLE_BRANCH
            - run:
                name: Publish @brightlayer-ui/react-native-template-authentication-typescript
                command: |
                  cd authentication-typescript && yarn publish:package -b $CIRCLE_BRANCH

    tag:
        docker:
            - image: circleci/node:14.18.1-browsers
        steps:
            - checkout
            - gh/setup
            - run:
                name: Tag @brightlayer-ui/react-native-template-blank
                command: |
                  cd blank && yarn tag:package -b $CIRCLE_BRANCH -s -blui-blank
            - run:
                name: Tag @brightlayer-ui/react-native-template-blank-typescript
                command: |
                  cd blank-typescript && yarn tag:package -b $CIRCLE_BRANCH -s -blui-blank-typescription
            - run:
                name: Tag @brightlayer-ui/react-native-template-routing
                command: |
                  cd routing && yarn tag:package -b $CIRCLE_BRANCH -s -blui-routing
            - run:
                name: Tag @brightlayer-ui/react-native-template-routing-typescript
                command: |
                  cd routing-typescript && yarn tag:package -b $CIRCLE_BRANCH -s -blui-routing-typescript
            - run:
                name: Tag @brightlayer-ui/react-native-template-authentication
                command: |
                  cd authentication && yarn tag:package -b $CIRCLE_BRANCH -s -blui-authentication
            - run:
                name: Tag @brightlayer-ui/react-native-template-authentication-typescript
                command: |
                  cd authentication-typescript && yarn tag:package -b $CIRCLE_BRANCH -s -blui-authentication-typescript

workflows:
    version: 2
    react-native-cli-templates:
        jobs:
            - build_project
            - publish:
                requires:
                    - build_project
                filters:
                    branches:
                        only:
                          - master
                          - dev
            - tag:
                requires:
                  - build_project
                filters:
                    branches:
                        only:
                          - master